version: 2
updates:
- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: monthly
    time: "23:30"
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "23:30"
  open-pull-requests-limit: 10
